require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config/*/*'
    - 'config/*'
    - 'Rakefile'


    - 'bin/*'
  AutoCorrect: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false
